---
version: '0.2'
env:
  variables:
    AWS_REGION: "us-east-1"
phases:
  install:
    runtime-versions:
      python: 3.9
      
  pre_build:
    commands:
      - yum install amazon-linux-extras
      - python3 -m venv /root/venv
      - . /root/venv/bin/activate
      - pip3 install pytest && pip3 install poetry
      - poetry install
      
  build:
    commands:
      - echo Running tests
      - pytest -s
