---
version: '0.2'
env:
  variables:
    AWS_REGION: "us-east-1"
phases:
  install:
    runtime-versions:
      python: 3.11
      
  pre_build:
    commands:
      - python3 -m venv /root/venv
      - . /root/venv/bin/activate
      - pip3 install pytest
      
  build:
    commands:
      - echo Running tests
      - python ./scripts/codedeploy-pg.py
