---
version: '0.2'
env:
  variables:
    AWS_REGION: "us-east-1"
phases:
  install:
    runtime-versions:
      python: 3.11
      
  pre_build:
    commands:
      - python3 -m venv /root/venv
      - . /root/venv/bin/activate
      - pip3 install boto3
      - pip3 install psycopg2-binary
      
  build:
    commands:
      - echo Running...
      - python ./scripts/codedeploy-pg.py $CODEBUILD_SRC_DIR_DB_Code $DEPLOY_METADATA_FILE
